### ISSUE TITLE
Port 80 and new gen 3 problems

### ISSUE THREAD

**Issue by scargill** [datech/node-red-contrib-amazon-echo#19]
Help - I'm a known happy user of Amazon-Echo node....  all has been well, I use user Pi (not root) - and I use port 8980 for the node - worked a treat fo weeks until yesterday when I replaced my generation 1 DOTS with generation 3... and all of a sudden the node won't work sny more - I am using port 80 on my PI for other  stuff - ie web pages - and I HAVE to use user pi for NR.

Someone please tell me there's a way around this - I have lots of stuff using nr-contrib-amazon-echo.

If Echo is insisting on sending to port 80 does this mean I have to move my existing web server and lots of other stuff to another port AND figure out how to port forward from 8980 to 80?

**Comment by fragolinux** [comment]
will this work redirecting port 80 to local 8980? As Peter's using port 8980:

sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8980

**Comment by scargill** [comment]
I'll try that thanks - already moved nginx to port 86 - that was easy... 2 references in /etc/nginx/sites-enabled....

**Comment by datech** [comment]
Port 80 is required for all new Echo devices, like Dot 3rd gen or Plus 2nd gen. They will try to connect to port 80 even if a different port is configured.

Port forwarding should resolve it. I added it as a possible solution in the [troubleshooting page]( 
https://github.com/datech/node-red-contrib-amazon-echo/wiki/Troubleshooting)

**Comment by fragolinux** [comment]
please add actual iptables config lines and not a generic tutorial on how to use iptables, because not everybody is good in using that :)

are these fine?

- sudo apt-get install iptables-persistent
- sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
- sudo iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8980
- sudo iptables-save > /etc/iptables/rules.v4
- sudo ip6tables-save > /etc/iptables/rules.v6

thanks

**Comment by scargill** [comment]
Done - resolved, thanks all.

**Comment by woody4165** [comment]
Hi all

I have NodeRed installed in a docker container in Ubuntu server.
I'm using Portainer to manage the containers and I don't have port 80 in use (checked with `sudo lsof -i -P -n `and with `netstat -tulpn | grep LISTEN`) in any other service.

Is there a way to add `--user 0` to run Node-Red with root user it, without regenerating the container or the container image?

Thanks

**Comment by datech** [comment]
Hello @woody4165 . If you want to run the Amazon Echo hub on port 80 you have to run Node-RED as root user. Another solution is to use port forwarding. iptables commands listed above should do the job

@fragolinux Thanks. I've just updated the wiki page. I've skipped apt-get commands as they are distribution specific. The interface name is also OS and configuration specific, but anyway, this should be a good starting point.

**Comment by vemeT5ak** [comment]
Hoping this helps someone. This worked for me as of 10 min ago.

sudo apt-get install iptables-persistent
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -p udp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -L
sudo sh -c "iptables-save > /etc/iptables.rules"
sudo apt-get install iptables-persistent


In Node Red, the "Amazon Alexa Hub" node needs to set to the whatever number port you set in the iptables. In my text above that number is 8080

**Comment by scargill** [comment]
You beat me to it, yes that should solve the discovery issue.

**Comment by vuiperez** [comment]
@vemeT5ak vemeT5ak

how are you i did the comands that you posted but still have on Amazon Echo hub " unable to start on port 80" . what should i do or what i did wrong?

**Comment by vuiperez** [comment]
done i didn't change to port 8080 :)
thanks

**Comment by EddyS83** [comment]
Hi together,
i've still a problem with using on same ip pihole on port 80...
If i forward the port to 8080 alexa works on node-red but my pihole not anymore. 
Do somebody have a solution or can suggest me a way?

**Comment by thalesmaoa** [comment]
@EddyS83, without having the ability to change Alexa port, you have to give up and change pihole

```
$ sudo nano /etc/lighttpd/lighttpd.conf
```

search for 

```
server.port = 80
```

and change it.

**Comment by fercod** [comment]
> Hoping this helps someone. This worked for me as of 10 min ago.
> 
> sudo apt-get install iptables-persistent sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 sudo iptables -t nat -A PREROUTING -p udp --dport 80 -j REDIRECT --to-port 8080 sudo iptables -t nat -L sudo sh -c "iptables-save > /etc/iptables.rules"
> 
> In Node Red, the "Amazon Echo Hub" node needs to set to the whatever number port you set in the iptables. In my text above that number is 8080

THANKS! This is a solution.
